// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sub/sub/sub.proto

package sub

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error_Code int32

const (
	Error_UNAUTHORIZED          Error_Code = 0
	Error_BAD_REQUEST           Error_Code = 1
	Error_INTERNAL_SERVER_ERROR Error_Code = 2
)

var Error_Code_name = map[int32]string{
	0: "UNAUTHORIZED",
	1: "BAD_REQUEST",
	2: "INTERNAL_SERVER_ERROR",
}

var Error_Code_value = map[string]int32{
	"UNAUTHORIZED":          0,
	"BAD_REQUEST":           1,
	"INTERNAL_SERVER_ERROR": 2,
}

func (x Error_Code) String() string {
	return proto.EnumName(Error_Code_name, int32(x))
}

func (Error_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_69dec0efa570a6a7, []int{2, 0}
}

type Request struct {
	Term1                int64    `protobuf:"varint,1,opt,name=term1,proto3" json:"term1,omitempty"`
	Term2                int64    `protobuf:"varint,2,opt,name=term2,proto3" json:"term2,omitempty"`
	IsAuthorized         bool     `protobuf:"varint,3,opt,name=isAuthorized,proto3" json:"isAuthorized,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_69dec0efa570a6a7, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetTerm1() int64 {
	if m != nil {
		return m.Term1
	}
	return 0
}

func (m *Request) GetTerm2() int64 {
	if m != nil {
		return m.Term2
	}
	return 0
}

func (m *Request) GetIsAuthorized() bool {
	if m != nil {
		return m.IsAuthorized
	}
	return false
}

type Response struct {
	Sub                  int64    `protobuf:"varint,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_69dec0efa570a6a7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSub() int64 {
	if m != nil {
		return m.Sub
	}
	return 0
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 Error_Code `protobuf:"varint,1,opt,name=code,proto3,enum=Error_Code" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_69dec0efa570a6a7, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() Error_Code {
	if m != nil {
		return m.Code
	}
	return Error_UNAUTHORIZED
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("Error_Code", Error_Code_name, Error_Code_value)
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() { proto.RegisterFile("sub/sub/sub.proto", fileDescriptor_69dec0efa570a6a7) }

var fileDescriptor_69dec0efa570a6a7 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0xa6, 0x7f, 0xa7, 0x45, 0xe3, 0xa2, 0x10, 0xff, 0x80, 0x25, 0xa7, 0x5e, 0x9a,
	0x62, 0x44, 0x04, 0x6f, 0xa9, 0x59, 0xb0, 0x20, 0x2d, 0x4e, 0x5b, 0xc1, 0x5e, 0x4a, 0x93, 0x0e,
	0x69, 0xa8, 0xe9, 0xc6, 0xdd, 0x44, 0xc4, 0x4f, 0xe0, 0xc7, 0x96, 0xa6, 0x0d, 0xe2, 0x61, 0x61,
	0xdf, 0x6f, 0xdf, 0x3e, 0x98, 0x79, 0x70, 0xa2, 0x32, 0xbf, 0x7f, 0x38, 0x76, 0x22, 0x45, 0x2a,
	0xac, 0x37, 0xa8, 0x23, 0x7d, 0x64, 0xa4, 0x52, 0x76, 0x0a, 0xd5, 0x94, 0x64, 0x7c, 0x63, 0x6a,
	0x1d, 0xad, 0xab, 0xe3, 0x5e, 0x14, 0xd4, 0x31, 0xcb, 0x7f, 0xd4, 0x61, 0x16, 0xb4, 0x23, 0xe5,
	0x66, 0xe9, 0x5a, 0xc8, 0xe8, 0x9b, 0x56, 0xa6, 0xde, 0xd1, 0xba, 0x0d, 0xfc, 0xc7, 0xac, 0x07,
	0x68, 0x20, 0xa9, 0x44, 0x6c, 0x15, 0x31, 0x03, 0x74, 0x95, 0xf9, 0x87, 0xe4, 0xdd, 0x95, 0x5d,
	0x41, 0x95, 0xa4, 0x14, 0x32, 0xcf, 0x6d, 0x39, 0x35, 0x9b, 0xef, 0x14, 0xee, 0xa1, 0xf5, 0xa3,
	0x41, 0x35, 0x07, 0xec, 0x1a, 0x2a, 0x81, 0x58, 0x51, 0xfe, 0xf5, 0xc8, 0x69, 0xed, 0x6d, 0xf6,
	0xa3, 0x58, 0x11, 0xe6, 0x0f, 0xcc, 0x84, 0x7a, 0x4c, 0x4a, 0x2d, 0x43, 0xca, 0xa3, 0x9a, 0x58,
	0x48, 0xcb, 0x83, 0xca, 0xce, 0xc7, 0x0c, 0x68, 0xcf, 0x46, 0xee, 0x6c, 0xfa, 0x34, 0xc6, 0xe1,
	0x9c, 0x7b, 0x46, 0x89, 0x1d, 0x43, 0x6b, 0xe0, 0x7a, 0x0b, 0xe4, 0x2f, 0x33, 0x3e, 0x99, 0x1a,
	0x1a, 0x3b, 0x87, 0xb3, 0xe1, 0x68, 0xca, 0x71, 0xe4, 0x3e, 0x2f, 0x26, 0x1c, 0x5f, 0x39, 0x2e,
	0x38, 0xe2, 0x18, 0x8d, 0xb2, 0x63, 0x81, 0x3e, 0xc9, 0x7c, 0x76, 0x09, 0x65, 0x4f, 0xb0, 0x86,
	0x7d, 0xd8, 0xd6, 0x45, 0xd3, 0x2e, 0x86, 0xb3, 0x4a, 0x83, 0xfb, 0xf9, 0x5d, 0x18, 0xa5, 0xeb,
	0xcc, 0xb7, 0x03, 0x11, 0xf7, 0x37, 0xcb, 0x6d, 0x98, 0x6d, 0xa2, 0x7e, 0x28, 0x93, 0xa0, 0x17,
	0x47, 0x81, 0x14, 0x8a, 0xe4, 0x67, 0x14, 0x90, 0xea, 0xd1, 0xd7, 0x32, 0x4e, 0xde, 0xa9, 0x28,
	0xc1, 0xaf, 0xe5, 0x2d, 0xdc, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x33, 0x93, 0xdd, 0x03, 0x9a,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SubClient is the client API for Sub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubClient interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type subClient struct {
	cc *grpc.ClientConn
}

func NewSubClient(cc *grpc.ClientConn) SubClient {
	return &subClient{cc}
}

func (c *subClient) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Sub/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubServer is the server API for Sub service.
type SubServer interface {
	Do(context.Context, *Request) (*Response, error)
}

// UnimplementedSubServer can be embedded to have forward compatible implementations.
type UnimplementedSubServer struct {
}

func (*UnimplementedSubServer) Do(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}

func RegisterSubServer(s *grpc.Server, srv SubServer) {
	s.RegisterService(&_Sub_serviceDesc, srv)
}

func _Sub_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Sub/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubServer).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Sub",
	HandlerType: (*SubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Sub_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sub/sub/sub.proto",
}
