// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sum/sum/sum.proto

// option go_package = "github.com/kanguki/grpc-microservices-example/sum/sum";

package sum

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error_Code int32

const (
	Error_UNAUTHORIZED          Error_Code = 0
	Error_BAD_REQUEST           Error_Code = 1
	Error_INTERNAL_SERVER_ERROR Error_Code = 2
)

var Error_Code_name = map[int32]string{
	0: "UNAUTHORIZED",
	1: "BAD_REQUEST",
	2: "INTERNAL_SERVER_ERROR",
}

var Error_Code_value = map[string]int32{
	"UNAUTHORIZED":          0,
	"BAD_REQUEST":           1,
	"INTERNAL_SERVER_ERROR": 2,
}

func (x Error_Code) String() string {
	return proto.EnumName(Error_Code_name, int32(x))
}

func (Error_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6ccf25e48e396282, []int{2, 0}
}

type Request struct {
	Term1                int64    `protobuf:"varint,1,opt,name=term1,proto3" json:"term1,omitempty"`
	Term2                int64    `protobuf:"varint,2,opt,name=term2,proto3" json:"term2,omitempty"`
	IsAuthorized         bool     `protobuf:"varint,3,opt,name=isAuthorized,proto3" json:"isAuthorized,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccf25e48e396282, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetTerm1() int64 {
	if m != nil {
		return m.Term1
	}
	return 0
}

func (m *Request) GetTerm2() int64 {
	if m != nil {
		return m.Term2
	}
	return 0
}

func (m *Request) GetIsAuthorized() bool {
	if m != nil {
		return m.IsAuthorized
	}
	return false
}

type Response struct {
	Sum                  int64    `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccf25e48e396282, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 Error_Code `protobuf:"varint,1,opt,name=code,proto3,enum=sum.Error_Code" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccf25e48e396282, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() Error_Code {
	if m != nil {
		return m.Code
	}
	return Error_UNAUTHORIZED
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("sum.Error_Code", Error_Code_name, Error_Code_value)
	proto.RegisterType((*Request)(nil), "sum.Request")
	proto.RegisterType((*Response)(nil), "sum.Response")
	proto.RegisterType((*Error)(nil), "sum.Error")
}

func init() { proto.RegisterFile("sum/sum/sum.proto", fileDescriptor_6ccf25e48e396282) }

var fileDescriptor_6ccf25e48e396282 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x9b, 0xa6, 0xfd, 0xb7, 0xff, 0x69, 0xb4, 0x71, 0x50, 0x88, 0x9e, 0xc2, 0xf6, 0x52,
	0x3c, 0x44, 0x8c, 0x77, 0x21, 0x9a, 0x05, 0x0b, 0x92, 0xe2, 0x24, 0x11, 0xf4, 0x12, 0xd4, 0x2c,
	0xda, 0x43, 0xdc, 0xba, 0x9b, 0x5c, 0xfc, 0x0c, 0x7e, 0x68, 0xc9, 0x26, 0xa5, 0x78, 0x58, 0xd8,
	0xf7, 0x9b, 0xd9, 0xb7, 0x33, 0x0f, 0x8e, 0x74, 0x53, 0x5d, 0xf4, 0x27, 0xd8, 0x2a, 0x59, 0x4b,
	0xb4, 0x75, 0x53, 0xb1, 0x27, 0x98, 0x90, 0xf8, 0x6a, 0x84, 0xae, 0xf1, 0x18, 0xc6, 0xb5, 0x50,
	0xd5, 0xa5, 0x67, 0xf9, 0xd6, 0xd2, 0xa6, 0x4e, 0xec, 0x68, 0xe8, 0x0d, 0xf7, 0x34, 0x44, 0x06,
	0xce, 0x46, 0x47, 0x4d, 0xfd, 0x21, 0xd5, 0xe6, 0x5b, 0x94, 0x9e, 0xed, 0x5b, 0xcb, 0x29, 0xfd,
	0x61, 0xec, 0x1a, 0xa6, 0x24, 0xf4, 0x56, 0x7e, 0x6a, 0x81, 0x2e, 0xb4, 0xbf, 0xf5, 0xce, 0xed,
	0x15, 0x7d, 0x18, 0x0b, 0xa5, 0xa4, 0x32, 0xbe, 0xb3, 0x10, 0x82, 0x76, 0x30, 0xde, 0x12, 0xea,
	0x0a, 0xec, 0xc7, 0x82, 0xb1, 0x01, 0xb8, 0x80, 0xd1, 0x9b, 0x2c, 0x85, 0x79, 0x7e, 0x18, 0xce,
	0xf7, 0xad, 0xc1, 0xad, 0x2c, 0x05, 0x99, 0x22, 0x7a, 0x30, 0xa9, 0x84, 0xd6, 0x2f, 0xef, 0xc2,
	0x58, 0xfe, 0xa7, 0x9d, 0x64, 0x31, 0x8c, 0xda, 0x3e, 0x74, 0xc1, 0xc9, 0x93, 0x28, 0xcf, 0xee,
	0xd6, 0xb4, 0x7a, 0xe6, 0xb1, 0x3b, 0xc0, 0x39, 0xcc, 0x6e, 0xa2, 0xb8, 0x20, 0xfe, 0x90, 0xf3,
	0x34, 0x73, 0x2d, 0x3c, 0x85, 0x93, 0x55, 0x92, 0x71, 0x4a, 0xa2, 0xfb, 0x22, 0xe5, 0xf4, 0xc8,
	0xa9, 0xe0, 0x44, 0x6b, 0x72, 0x87, 0xe1, 0x39, 0xd8, 0x69, 0x53, 0xe1, 0x02, 0x86, 0xb1, 0x44,
	0xc7, 0xcc, 0xd0, 0x27, 0x77, 0x76, 0xd0, 0xab, 0x6e, 0x59, 0x36, 0x78, 0xfd, 0x67, 0x12, 0xbe,
	0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xae, 0x09, 0x40, 0x21, 0x76, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SumClient is the client API for Sum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumClient interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type sumClient struct {
	cc *grpc.ClientConn
}

func NewSumClient(cc *grpc.ClientConn) SumClient {
	return &sumClient{cc}
}

func (c *sumClient) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/sum.Sum/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumServer is the server API for Sum service.
type SumServer interface {
	Do(context.Context, *Request) (*Response, error)
}

// UnimplementedSumServer can be embedded to have forward compatible implementations.
type UnimplementedSumServer struct {
}

func (*UnimplementedSumServer) Do(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}

func RegisterSumServer(s *grpc.Server, srv SumServer) {
	s.RegisterService(&_Sum_serviceDesc, srv)
}

func _Sum_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sum.Sum/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumServer).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sum_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sum.Sum",
	HandlerType: (*SumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Sum_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sum/sum/sum.proto",
}
