// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mul/mul/mul.proto

package mul

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error_Code int32

const (
	Error_UNAUTHORIZED          Error_Code = 0
	Error_BAD_REQUEST           Error_Code = 1
	Error_INTERNAL_SERVER_ERROR Error_Code = 2
)

var Error_Code_name = map[int32]string{
	0: "UNAUTHORIZED",
	1: "BAD_REQUEST",
	2: "INTERNAL_SERVER_ERROR",
}

var Error_Code_value = map[string]int32{
	"UNAUTHORIZED":          0,
	"BAD_REQUEST":           1,
	"INTERNAL_SERVER_ERROR": 2,
}

func (x Error_Code) String() string {
	return proto.EnumName(Error_Code_name, int32(x))
}

func (Error_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9a7215b6e218716d, []int{2, 0}
}

type Request struct {
	Term1                int64    `protobuf:"varint,1,opt,name=term1,proto3" json:"term1,omitempty"`
	Term2                int64    `protobuf:"varint,2,opt,name=term2,proto3" json:"term2,omitempty"`
	IsAuthorized         bool     `protobuf:"varint,3,opt,name=isAuthorized,proto3" json:"isAuthorized,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a7215b6e218716d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetTerm1() int64 {
	if m != nil {
		return m.Term1
	}
	return 0
}

func (m *Request) GetTerm2() int64 {
	if m != nil {
		return m.Term2
	}
	return 0
}

func (m *Request) GetIsAuthorized() bool {
	if m != nil {
		return m.IsAuthorized
	}
	return false
}

type Response struct {
	Mul                  int64    `protobuf:"varint,1,opt,name=mul,proto3" json:"mul,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a7215b6e218716d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMul() int64 {
	if m != nil {
		return m.Mul
	}
	return 0
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 Error_Code `protobuf:"varint,1,opt,name=code,proto3,enum=Error_Code" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a7215b6e218716d, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() Error_Code {
	if m != nil {
		return m.Code
	}
	return Error_UNAUTHORIZED
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("Error_Code", Error_Code_name, Error_Code_value)
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() { proto.RegisterFile("mul/mul/mul.proto", fileDescriptor_9a7215b6e218716d) }

var fileDescriptor_9a7215b6e218716d = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x6b, 0xea, 0x40,
	0x14, 0xc5, 0x8d, 0xf1, 0xef, 0x55, 0xde, 0xcb, 0x1b, 0x5e, 0x21, 0xfd, 0x03, 0x95, 0xac, 0xdc,
	0x18, 0x69, 0x4a, 0x29, 0x74, 0x17, 0x9b, 0x81, 0x0a, 0xad, 0xd2, 0xab, 0x16, 0xea, 0x46, 0x34,
	0x5e, 0x62, 0x30, 0x71, 0xd2, 0x99, 0xa4, 0x94, 0x7e, 0x82, 0x7e, 0xec, 0x62, 0x34, 0x94, 0x2e,
	0x06, 0xe6, 0xfc, 0xe6, 0xcc, 0x81, 0x7b, 0x0f, 0xfc, 0x8b, 0xb3, 0xa8, 0x7f, 0x3c, 0x76, 0x22,
	0x45, 0x2a, 0xac, 0x57, 0xa8, 0x23, 0xbd, 0x65, 0xa4, 0x52, 0xf6, 0x1f, 0xaa, 0x29, 0xc9, 0xf8,
	0xca, 0xd4, 0x3a, 0x5a, 0x57, 0xc7, 0x83, 0x28, 0xa8, 0x63, 0x96, 0x7f, 0xa8, 0xc3, 0x2c, 0x68,
	0x87, 0xca, 0xcd, 0xd2, 0x8d, 0x90, 0xe1, 0x27, 0xad, 0x4d, 0xbd, 0xa3, 0x75, 0x1b, 0xf8, 0x8b,
	0x59, 0x77, 0xd0, 0x40, 0x52, 0x89, 0xd8, 0x29, 0x62, 0x06, 0xe8, 0x71, 0x16, 0x1d, 0x93, 0xf7,
	0x57, 0x76, 0x01, 0x55, 0x92, 0x52, 0xc8, 0x3c, 0xb7, 0xe5, 0xd4, 0x6c, 0xbe, 0x57, 0x78, 0x80,
	0xd6, 0x97, 0x06, 0xd5, 0x1c, 0xb0, 0x4b, 0xa8, 0xf8, 0x62, 0x4d, 0xf9, 0xd7, 0x3f, 0x4e, 0xeb,
	0x60, 0xb3, 0xef, 0xc5, 0x9a, 0x30, 0x7f, 0x60, 0x26, 0xd4, 0x63, 0x52, 0x6a, 0x19, 0x50, 0x1e,
	0xd5, 0xc4, 0x42, 0x5a, 0x1e, 0x54, 0xf6, 0x3e, 0x66, 0x40, 0x7b, 0x36, 0x72, 0x67, 0xd3, 0x87,
	0x31, 0x0e, 0xe7, 0xdc, 0x33, 0x4a, 0xec, 0x2f, 0xb4, 0x06, 0xae, 0xb7, 0x40, 0xfe, 0x3c, 0xe3,
	0x93, 0xa9, 0xa1, 0xb1, 0x53, 0x38, 0x19, 0x8e, 0xa6, 0x1c, 0x47, 0xee, 0xe3, 0x62, 0xc2, 0xf1,
	0x85, 0xe3, 0x82, 0x23, 0x8e, 0xd1, 0x28, 0x3b, 0x16, 0xe8, 0x4f, 0x59, 0xc4, 0xce, 0xa1, 0xec,
	0x09, 0xd6, 0xb0, 0x8f, 0xdb, 0x3a, 0x6b, 0xda, 0xc5, 0x70, 0x56, 0x69, 0x70, 0x3b, 0xbf, 0x09,
	0xc2, 0x74, 0x93, 0xad, 0x6c, 0x5f, 0xc4, 0xfd, 0xed, 0x72, 0x17, 0x64, 0xdb, 0xb0, 0x1f, 0xc8,
	0xc4, 0xef, 0xc5, 0xa1, 0x2f, 0x85, 0x22, 0xf9, 0x1e, 0xfa, 0xa4, 0x7a, 0xf4, 0xb1, 0x8c, 0x93,
	0x88, 0x8a, 0x12, 0x56, 0xb5, 0xbc, 0x85, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xab,
	0x14, 0xd3, 0x9a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MulClient is the client API for Mul service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MulClient interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type mulClient struct {
	cc *grpc.ClientConn
}

func NewMulClient(cc *grpc.ClientConn) MulClient {
	return &mulClient{cc}
}

func (c *mulClient) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Mul/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MulServer is the server API for Mul service.
type MulServer interface {
	Do(context.Context, *Request) (*Response, error)
}

// UnimplementedMulServer can be embedded to have forward compatible implementations.
type UnimplementedMulServer struct {
}

func (*UnimplementedMulServer) Do(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}

func RegisterMulServer(s *grpc.Server, srv MulServer) {
	s.RegisterService(&_Mul_serviceDesc, srv)
}

func _Mul_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MulServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mul/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MulServer).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mul_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Mul",
	HandlerType: (*MulServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Mul_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mul/mul/mul.proto",
}
